Welding Tool Animation
pariahstation/Pariah-Station pull request #665
Opened 2022-04-27 06:35 UTC by Tokorizo

## About The Pull Request
Original PR: https://github.com/TauCetiStation/TauCetiClassic/pull/6540

Adds welding animations when used on walls.

## Why It's Good For The Game

A nice little animation to signal someone breaking into places, plus it's pretty well done.
![102169561-8e203980-3ea3-11eb-982f-8629edee62f3](https://user-images.githubusercontent.com/62493359/165456044-27a869c5-3252-4a50-8b80-3f5bb60c82d7.gif)

![dreamseeker_2dUSJmgC4y](https://user-images.githubusercontent.com/62493359/165455987-2917c11a-14e2-4a4e-adf6-50bd9d4e212c.gif)

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-04-27 12:26 UTC, SabreML requested changes
Unless I'm missing something somewhere, it seems like this could be made a lot simpler and cleaner by just putting everything onto `/obj/item/weldingtool`, rather than adding things to `/obj/item/proc/use_tool()` and `/obj/item` that are only ever used by welding tools.

E.g:
```dm
/obj/item/weldingtool
	(...)
	/// An image effect for displaying a welding effect for items that support it.
	var/image/welding_sparks

/obj/item/weldingtool/Initialize(mapload)
	. = ..()
	(...)
	welding_sparks = image('code/modules/welding_sparks/icons/welding_effect.dmi', "welding_sparks", GASFIRE_LAYER)
	welding_sparks.plane = ABOVE_LIGHTING_PLANE

/obj/item/weldingtool/Destroy(force)
	QDEL_NULL(welding_sparks)
	return ..()

(...)

/obj/item/weldingtool/use_tool(atom/target, mob/living/user, delay, amount, volume, datum/callback/extra_checks)
	target.add_overlay(welding_sparks)
	. = ..()
	target.cut_overlay(welding_sparks)

2022-04-28 02:01 UTC, Kapu1178 requested changes

2022-04-28 02:01 UTC, Kapu1178 commented on code/game/objects/items/tools/weldingtool.dm
> +	welding_sparks = image('code/modules/welding_sparks/icons/welding_effect.dmi', "welding_sparks", GASFIRE_LAYER)
Icons do not belong in modules. Icons belong in `/icons`

2022-04-28 02:01 UTC, Kapu1178 commented on code/game/objects/items/tools/weldingtool.dm
> +	var/image/welding_sparks
Make this a static var and just set it here, doing it in initialize is a waste

2022-04-29 13:26 UTC, SabreML commented on code/game/objects/items.dm
> +GLOBAL_DATUM_INIT(welding_sparks, /mutable_appearance, mutable_appearance('code/modules/welding_sparks/icons/welding_effect.dmi', "welding_sparks", GASFIRE_LAYER, ABOVE_LIGHTING_PLANE))
Should be fine now other than moving the dmi file into `/icons/effects`.

2022-04-30 00:06 UTC, SabreML approved these changes

2022-04-30 01:13 UTC, francinum approved these changes

2022-04-30 01:31 UTC, axietheaxolotl approved these changes
I am really not a fan of setting a precedent of animations being a thing. Animations work, for specific things, or things that need animation, i.e. vortex, lord scrunguloth, etc. Welding isn't something that needs an animation, should every long skill check have an animation? Should we give n-spect scanning an animation? I don't like setting a precedent of things having animations because I know from experience they are awful to do. Especially with something so common, the animation in a lone setting is good, but within the confines of everything?

That being said, it's _fine_. But if I get one person asking for an animation because "muh welding" does it, I will autistic screech the loudest I told you so.

2022-04-30 01:31 UTC, merged