Adds Cryopods (again)
pariahstation/Pariah-Station pull request #674
Opened 2022-04-28 03:42 UTC by fighterslam

## About The Pull Request
I added Cryopods to our maps (again)

## Why It's Good For The Game
we can go to sleep now

## Changelog

:cl:
add: Adds cryopods to all the maps. Again.
/:cl:

2022-04-28 14:47 UTC, SabreML requested changes
It'd be worth putting some `/obj/effect/landmark/navigate_destination`'s on the doors of the new areas, that way players will always be able to find them with the navigate button.
<hr>

<details>
<summary><b>Map review:</b></summary>

**Delta:**
This room could really benefit from having a light installed somewhere:
![image](https://user-images.githubusercontent.com/57483089/165774564-cfaffc13-626f-4668-9d9c-4cecde378dc5.png)
<hr>

**Icebox:**
The area of the two wall tiles at the bottom needs changing, and an added light might be good here as well:
![image](https://user-images.githubusercontent.com/57483089/165775607-d873afbd-779b-4e0a-8687-5382b8cad652.png) ![image](https://user-images.githubusercontent.com/57483089/165775710-7a6676ce-71c3-4bfc-a3ec-d931cfdfe673.png)
Also, the railing around the top right cryopod looks a bit odd, but that might just be me.
<hr>

**Kilo:**
👍
<hr>

**Meta:**
Again it could do with a light, but LGTM otherwise:
![image](https://user-images.githubusercontent.com/57483089/165778129-129342ab-a7a7-4434-ac44-a6c5f4478163.png)
<hr>

**Tram:**
*Definitely* need some lighting in here:
![image](https://user-images.githubusercontent.com/57483089/165778942-e89db188-ba73-48d3-bfb2-40fd1e13eb12.png)
</details>

2022-05-02 20:08 UTC, fighterslam commented
@SabreML Added lights and stuff.

2022-05-02 21:01 UTC, SabreML reviewed
Final thing then it should be good to merge:
![image](https://user-images.githubusercontent.com/57483089/166326904-4971821a-09b0-42c2-83b8-cb4d204c0a1d.png)
Can you move this camera over to somewhere on the opposite wall?

2022-05-02 22:21 UTC, SabreML approved these changes

2022-05-02 22:22 UTC, merged