Adds Roleplay And Subtler Stuff
pariahstation/Pariah-Station pull request #69
Opened 2022-03-22 08:48 UTC by Tokorizo

## About The Pull Request

Original PR's I ported:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/872/files
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9395/files

Ports two things, better roleplay mechanics for /me and general typing stuff I didn't bother to research, and subtle and subtler for private messaging without a ghost being able to listen.

## Why It's Good For The Game

Adds more content to the roleplay side of the game and subtle anti-ghost is critical for reasons.

## Changelog

:cl:
add: Added LOOC, subtle, and subtler. Tweaked WHO too.
qol: Emotes starting with a comma (,) or an apostrophe (') will no longer have an awkward space between the mob name and said comma.
code: Improved a bit some of the subtle and subtler code.
/:cl:

2022-03-22 09:34 UTC, michaelyesok commented
hmm yes roleplay mechanics
![image](https://user-images.githubusercontent.com/84622738/159450339-13b1796d-2c70-40be-9a35-363ea4d7a79c.png)

2022-03-25 17:13 UTC, E-MonaRhg requested changes
`>"roleplay mechanics"`
`>PR 69`

Anyways I don't know much about "subtle" and "subtler" stuff, or what its used for, but if you think this is what this codebase needs, then okay.

2022-03-25 17:13 UTC, E-MonaRhg commented on code/datums/emotes.dm
> +	// PARIAH EDIT START - Better emotes - Original: var/dchatmsg = "<b>[user]</b> [msg]"
We ought to keep the comment styles like:
```
//original //ORIGINAL
changed //PARIAH EDIT
```
rather than this

2022-03-25 17:13 UTC, E-MonaRhg commented on code/datums/emotes.dm
> +		user.audible_message(msg, deaf_message = "<span class='emote'>You see how <b>[user]</b>[space][msg]</span>", audible_message_flags = EMOTE_MESSAGE, separation = space) // PARIAH EDIT ADDITION - Ori
Comment styling

2022-03-25 17:13 UTC, E-MonaRhg commented on code/datums/emotes.dm
> +		user.visible_message(msg, blind_message = "<span class='emote'>You hear how <b>[user]</b>[space][msg]</span>", visible_message_flags = EMOTE_MESSAGE, separation = space) // PARIAH EDIT ADDITION - O
Comment styling

2022-03-25 17:13 UTC, E-MonaRhg commented on code/game/atoms.dm
> +		if(LOG_SUBTLER)
No comment regarding modularisation

2022-03-25 17:13 UTC, E-MonaRhg commented on code/game/objects/structures/beds_chairs/sofa.dm
> +// Ported from Pariah
Autoreplacer moment

2022-03-25 17:13 UTC, E-MonaRhg commented on code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
> +/mob/living/simple_animal/hostile/megafauna/dragon/visible_message(message, self_message, blind_message, vision_distance = DEFAULT_MESSAGE_RANGE, list/ignored_mobs, visible_message_flags = NONE, sepa
Comment styling

2022-03-25 17:13 UTC, E-MonaRhg commented on code/modules/mob/mob.dm
> + * * separation (otional) is what goes between the name of the person and the message, defaults to " ". PARIAH ADDITION
Comment styling but up to you, I'd prefer `PARIAH EDIT ADDITION`

2022-03-28 01:38 UTC, Zonespace27 commented
Unless you're an ERP codebase, I don't really think subtle/subtler (especially subtler, that's just meant so ghosts can't snoop on your ERP) are warranted

2022-03-28 11:51 UTC, Tokorizo commented
> that's

ERP will be allowed and we will be enforcing a rule to use subtle for any descriptive actions. The general summary.

2022-03-28 19:42 UTC, Tokorizo commented
``user.audible_message_subtler(message = subtler_message, hearing_distance = 1, ignored_mobs = GLOB.dead_mob_list, separation = space)``

PR works normally, the only issue that doesn't seem to cause errors is this line giving a bad keyword argument.

2022-03-29 05:52 UTC, Tokorizo commented
READY FOR REVIEW AAAAAA @E-MonaRhg

2022-03-29 12:51 UTC, E-MonaRhg approved these changes
LGTM I suppose

2022-03-29 13:41 UTC, merged