Progression traitor is now optional
pariahstation/Pariah-Station pull request #726
Opened 2022-05-17 11:31 UTC by Cenrus

## About The Pull Request

Traitors can now decide if they want to use progression based objectives instead of pursuing their default steal/assassinate/escape ones.

Added new uplink option named Challenge Mode, it costs all of your TC (20) to try and counteract snowballing, and unlocks the uplinks objective menu, allowing you to gain back your lost TC with enough effort.

## Why It's Good For The Game

Some traitors prefer the more aggressive style of progression objectives, and this adds back some lost features such as Romerol and the battlecruiser as final objectives for them to complete.

## Changelog

:cl:
add: Traitors now have the option to do progression objectives
/:cl:

2022-05-17 12:00 UTC, BrotherHangyul commented
_Might_ be beneficial to lower the price for Challenge mode to something like 15-18 TC, just so the traitor can still get basic tools. It's still possible to complete the objectives with just station tools, yes, but having access to something like a doorjack / EMP / just a better toolset might make it slightly more enjoyable. Don't take what I say too seriously though, I'm bad at balance.

2022-05-17 12:38 UTC, Cenrus commented on code/modules/uplink/uplink_items/bundle.dm
> +	name = "Challenge Mode"
I couldn't think of a better name. sorry.

2022-05-17 12:38 UTC, Tokorizo requested changes
I have a few issues with this PR, mostly the balance behind prog tots being an option route when we already have something that fills that niche called Contractors.

Prog tot is a bit of a messy snowball, depending on the amount of crew around and security, its incredibly easy to snowball infamously and TC by killing station pets and breaking into departments with no resistance. Id like to see some discussion on the github before I go forward with this, but the TLDR is simply; We have a niche for this, its called contractors.

2022-05-19 05:49 UTC, Zonespace27 commented
Contractor Shill/Creator/Enthusiast here, i would highly appreciate more content for contractors instead of this, which seems... to fall in pretty much the same category, as said above.

2022-05-19 14:38 UTC, Cenrus commented
I understand your concerns about the snowballing and I'm starting to doubt if traitor progression is actually balanced myself. I'm closing this for now, and I'll think of other ways to implement final objectives back into the game

2022-05-19 14:38 UTC, closed without merging